x-env: &app-env
  FOO: ONE
  BAR: TWO

services:
  nginx:
    image: nginx:latest
    container_name: sample-app-nginx-1
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php
  php:
    image: sample-app-php:8.2-fpm
    build:
      dockerfile: ./php.Dockerfile
    container_name: sample-app-php-1
    environment:
      <<: *app-env
      FOO: ANOTHER
      BAZZ: "Lorem ipsum"
    volumes:
      - .:/app
    entrypoint: ["php-entrypoint"]
    command: ["php-fpm"]

  mysql:
    image: mysql:8.1
    container_name: sample-app-mysql-1
    ports:
      - "23306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  mailcatcher:
    image: schickling/mailcatcher
    container_name: sample-app-mailcatcher-1
    ports:
      - 1080:1080

