x-env: &app-env
  FOO: ONE
  BAR: TWO

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    depends_on:
      - php
  php:
#    image: php:8.2-fpm
    build:
      dockerfile: ./php.Dockerfile
    environment:
      <<: *app-env
      FOO: ANOTHER
      BAZZ: "Lorem ipsum"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.1
    ports:
      - "23306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d


