x-env: &app-env
  FOO: ONE
  BAR: TWO

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    environment:
      <<: *app-env
      FOO: ANOTHER
    volumes:
      - .:/app

